# ~/.config/alacritty/alacritty.toml
[colors.bright]
black   = "0x414868"
red     = "0xf7768e"
green   = "0x9ece6a"
yellow  = "0xe0af68"
blue    = "0x7aa2f7"
magenta = "0xbb9af7"
cyan    = "0x7dcfff"
white   = "0xc0caf5"

[colors.normal]
black   = "0x1e1e2e"
red     = "0xf7768e"
green   = "0x9ece6a"
yellow  = "0xe0af68"
blue    = "0x7aa2f7"
magenta = "0xbb9af7"
cyan    = "0x7dcfff"
white   = "0xc0caf5"

[colors.primary]
background = "0x1e1e2e"
foreground = "0xc0caf5"

[font]
normal.family = "Hack Nerd Font"
normal.style = "Regular"
bold.family = "Hack Nerd Font"
bold.style = "Bold"
italic.family = "Hack Nerd Font"
italic.style = "Italic"
bold_italic.family = "Hack Nerd Font"
bold_italic.style = "Bold Italic"
size = 12

[window]
dynamic_title = true
padding.x = 5
padding.y = 5
opacity = 0.95

[cursor.style]
shape                 = "Beam"
blinking              = "Always"

[cursor.vi_mode_style]
shape                 = "Beam"
blinking              = "Off"

[mouse]
hide_when_typing = true

[selection]
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"

[terminal.shell]
program = "/usr/bin/zsh"
args = []
