[colors.bright]
black = "0x414868"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xc0caf5"
yellow = "0xe0af68"

[colors.normal]
black = "0x1e1e2e"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xa9b1d6"
yellow = "0xe0af68"

[colors.primary]
background = "0x1e1e2e"
foreground = "0xc0caf5"

[cursor]
style = { shape = "Beam", blinking = "Always"}
vi_mode_style = "None"
thickness = 0.11

[font]
size = 11.0

[font.bold]
family = "Hack Nerd Font"

[font.italic]
family = "Hack Nerd Font"

[font.normal]
family = "Hack Nerd Font"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
mouse = "Middle"
action = "PasteSelection"

[scrolling]
history = 10000
multiplier = 3

[selection]
semantic_escape_chars = ''',â”‚`|:"' ()[]{}<>'''

[terminal.shell]
program = "/usr/bin/zsh"
args = [ ]

[window]
dynamic_title = true
opacity = 0.97

[window.padding]
x = 2
y = 2
